// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseDocsFontMatter(arg1) {
  return window["go"]["docparse"]["ParseService"]["ParseDocsFontMatter"](arg1);
}

export function ParseToTree(arg1) {
  return window["go"]["docparse"]["ParseService"]["ParseToTree"](arg1);
}
