// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { docparse } from "../models";

export function ParseDocsFontMatter(arg1: string): Promise<Record<string, any>>;

export function ParseToTree(arg1: string): Promise<docparse.DocsTreeNode>;
