// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyTemplateFile(arg1:string,arg2:string,arg3:Record<string, Record<string, string>>):Promise<void>;

export function CreateProject(arg1:string,arg2:Record<string, Record<string, string>>):Promise<string>;

export function GetNodeVersion():Promise<string>;

export function GetNpmVersion():Promise<string>;
